### ISSUE TITLE
Togo Configure fails on RHEL 6.4

### ISSUE THREAD

**Issue by genereese** [genereese/togo#12]
User-reported issue via email:

I have followed the quickstart instructions and successfully built and installed the RPM on RHEL 6.4. However when trying to run the configure command I get the following error:

togo configure -n "Blah" -e "blah@blah.com"
Setting name...
Traceback (most recent call last):
  File "/usr/local/bin/togo", line 975, in <module>
    togo = Application()
  File "/usr/local/bin/togo", line 175, in __init__
    self.preferenceSetName(args.preference_name)
  File "/usr/local/bin/togo", line 281, in preferenceSetName
    p.name = name
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python2.6/site-packages/sqlobject/main.py", line 1040, in _SO_setValue
    dbValue)])
  File "/usr/lib/python2.6/site-packages/sqlobject/dbconnection.py", line 511, in _SO_update
    self.sqlrepr(so.id)))
  File "/usr/lib/python2.6/site-packages/sqlobject/dbconnection.py", line 337, in query
    return self._runWithConnection(self._query, s)
  File "/usr/lib/python2.6/site-packages/sqlobject/dbconnection.py", line 252, in _runWithConnection
    self.releaseConnection(conn)
  File "/usr/lib/python2.6/site-packages/sqlobject/sqlite/sqliteconnection.py", line 143, in releaseConnection
    DBAPI.releaseConnection(self, conn, explicit=explicit)
  File "/usr/lib/python2.6/site-packages/sqlobject/dbconnection.py", line 294, in releaseConnection
    conn.commit()
sqlite3.ProgrammingError: Cannot operate on a closed database.

**Comment by genereese** [comment]
It looks like this is an issue with how older python-sqlobject libraries handle the connection close. I'll have it fixed in the next release.

**Comment by genereese** [comment]
Removed premature closure of preferences database in latest release which should have fixed this issue.
